fix: new fix

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -83,6 +83,8 @@ jobs:
     needs: [changes, testing, set-vars]
     if: needs.changes.outputs.frontend == 'true'
     runs-on: ubuntu-latest
+    outputs:
+      image_tag: ${{ steps.get_tag.outputs.image_tag }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -105,12 +107,22 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Set frontend image tag
+        id: get_tag
         run: |
+          git fetch --tags
           if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
-          else
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
+          TAG=$(git describe --tags --abbrev=0 || echo "")
+            if [[ $TAG == v* ]]; then
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:$TAG" >> $GITHUB_ENV
+             echo "image_tag=$TAG" >> $GITHUB_OUTPUT
+            else
+             echo "Error: No semantic tag found"
+             exit 1
+            fi
+           else
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
           fi
+  
 
       - name: Build and push frontend image
         uses: docker/build-push-action@v5
@@ -125,7 +137,7 @@ jobs:
       - name: Upload frontend artifact
         uses: actions/upload-artifact@v4
         with:
-          name: frontend-build-${{ github.ref_name }}-${{ needs.set-vars.outputs.short_sha }}
+          name: frontend-build-${{ github.ref_name }}-${{ needs.frontend.outputs.image_tag }}
           path: frontend/dist/
 
       - name: Move updated docker cache
@@ -143,7 +155,7 @@ jobs:
       - name: Download frontend artifact
         uses: actions/download-artifact@v4
         with:
-          name: frontend-build-${{ github.ref_name }}-${{ needs.set-vars.outputs.short_sha }}
+          name: frontend-build-${{ github.ref_name }}-${{ needs.frontend.outputs.image_tag }}
           path: dist
 
       - name: Deploy to GitHub Pages
@@ -171,7 +183,7 @@ jobs:
         run: |
           trivy image --format template --template @html.tpl \
             -o frontend-trivy-report.html \
-            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:prod-${{ needs.set-vars.outputs.short_sha }}
+            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:${{ needs.frontend.outputs.image_tag }}
 
       - name: Upload Trivy HTML report
         uses: actions/upload-artifact@v4
@@ -198,8 +210,7 @@ jobs:
         run: |
           trivy image --format template --template @html.tpl \
             -o backend1-trivy-report.html \
-            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:prod-${{ needs.set-vars.outputs.short_sha }}
-
+            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:${{ needs.backend1.outputs.image_tag }}
       - name: Upload Trivy HTML report
         uses: actions/upload-artifact@v4
         with:
@@ -225,7 +236,7 @@ jobs:
         run: |
           trivy image --format template --template @html.tpl \
             -o backend2-trivy-report.html \
-            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:prod-${{ needs.set-vars.outputs.short_sha }}
+            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend2:${{ needs.backend2.outputs.image_tag }}
 
       - name: Upload Trivy HTML report
         uses: actions/upload-artifact@v4
@@ -284,6 +295,8 @@ jobs:
     needs: [changes, testing, set-vars]
     if: needs.changes.outputs.backend1 == 'true'
     runs-on: ubuntu-latest
+    outputs:
+      image_tag: ${{ steps.get_tag_b1.outputs.image_tag }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -298,12 +311,22 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Set backend1 image tag
+        id: get_tag_b1
         run: |
+          git fetch --tags
           if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
-          else
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
+          TAG=$(git describe --tags --abbrev=0 || echo "")
+            if [[ $TAG == v* ]]; then
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:$TAG" >> $GITHUB_ENV
+             echo "image_tag=$TAG" >> $GITHUB_OUTPUT
+            else
+             echo "Error: No semantic tag found"
+             exit 1
+            fi
+           else
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
           fi
+ 
 
       - name: Build and push backend1 image
         uses: docker/build-push-action@v5
@@ -324,6 +347,8 @@ jobs:
     needs: [changes, testing, set-vars]
     if: needs.changes.outputs.backend2 == 'true'
     runs-on: ubuntu-latest
+    outputs:
+      image_tag: ${{ steps.get_tag_b2.outputs.image_tag }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -338,12 +363,22 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Set backend2 image tag
+        id: get_tag_b2
         run: |
+          git fetch --tags
           if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend2:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
-          else
-            echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend2:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
+          TAG=$(git describe --tags --abbrev=0 || echo "")
+            if [[ $TAG == v* ]]; then
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:$TAG" >> $GITHUB_ENV
+             echo "image_tag=$TAG" >> $GITHUB_OUTPUT
+            else
+             echo "Error: No semantic tag found"
+             exit 1
+            fi
+           else
+             echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_ENV
           fi
+   
 
       - name: Build and push backend2 image
         uses: docker/build-push-action@v5
@@ -418,10 +453,9 @@ jobs:
           chmod 600 1sshkey
           ssh -i './1sshkey' ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
           echo "hello world" >> hello.txt
-          export TAG=${{ needs.set-vars.outputs.short_sha }}
-          docker pull pratik12321/blogapp-backend2:prod-$TAG
-          docker pull pratik12321/blogapp-backend1:prod-$TAG
-          docker pull pratik12321/blogapp-frontend:prod-$TAG
+          docker pull pratik12321/blogapp-backend2:${{ needs.backend2.outputs.image_tag }}
+          docker pull pratik12321/blogapp-backend1:${{ needs.backend1.outputs.image_tag }}
+          docker pull pratik12321/blogapp-frontend:${{ needs.backend1.outputs.image_tag }}
           
           docker rm -f backend1 backend2 frontend || true
           
@@ -430,15 +464,15 @@ jobs:
           docker run -d --name backend1 \
           --network backend-network \
           -p 3000:3000 \
-          pratik12321/blogapp-backend1:prod-$TAG
+          pratik12321/blogapp-backend1:${{ needs.backend1.outputs.image_tag }}
 
           docker run -d --name backend2 \
           --network backend-network \
           -p 3001:3001 \
-          pratik12321/blogapp-backend2:prod-$TAG
+          pratik12321/blogapp-backend2:${{ needs.backend2.outputs.image_tag }}
 
           docker run -d --name frontend \
           --network backend-network \
           -p 5173:5173 \
-          pratik12321/blogapp-frontend:prod-$TAG
+          pratik12321/blogapp-frontend:${{ needs.frontend.outputs.image_tag }}
           EOF
